### ISSUE TITLE
Resumable encrypted stream?

### ISSUE THREAD

**Issue by iazel** [tom25519/alkali#4]
Hello,

I'm working on a resumable file upload for my project, but I want to always encrypt data whenever I write to disk. This sounds like the perfect job for encrypted streams, but I'm not sure on how to handle the "resumable" part.

What I wish to do, would be to save the final stream state on close, then once I need to upload more data, I could read this record, repopulate stream state and keep going from there. As far as I can see, this isn't possible because stream state is private and not accessible.

What would you suggest for such a case? Would it be worth to expose such state?

Thanks once again for your time :pray:

**Comment by tom25519** [comment]
Hey, I'm sorry this has taken so long to get to. I'm sure you've found your own solution to this by now, but I'll just give my two cents: I think this use-case goes beyond the design goals of the `crypto_secretstream` API, and a more robust cryptographic construction is necessary.

Looking at the [secretstream algorithm](https://doc.libsodium.org/secret-key_cryptography/secretstream#algorithm) and [state struct definition](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/include/sodium/crypto_secretstream_xchacha20poly1305.h#L56-L60), a major potential issue I see immediately with doing this is the possibility of nonce reuse. Suppose we have an application that can save the stream state (which just amounts to the current stream key & nonce) and later resume from that state. If I can convince that application to resume the stream multiple times from the same saved state object, then we end up using the same key + nonce pair for ChaCha20-Poly1305 multiple times, which is game over (any passive attacker can trivially recover plaintext messages).

Obviously you could argue that the solution is to design your applications such that they can never resume from the same state, but this feels a *lot* more brittle than the original construction, especially in an environment where multiple instances of such an application are running concurrently (certainly I would want to see some kind of concurrent locking mechanism on the state record to feel remotely safe about it). My initial thought for what you would actually want here would be a new secretstream with a new key each time you resume sending the file, which incorporates the final MAC from the previous stream into its initial state calculation. But at this point, we're functionally rolling our own crypto - this kind of thing has a lot of footguns, and definitely requires a more formal approach in its design.

It's for reasons like this that I feel the best approach for this library is to treat objects like this as opaque implementation details which downstream users should not have access to. A design goal of this library is absolutely to remove footguns wherever possible, and this feels more like adding one in. Therefore, unless there are other compelling reasons to expose this state pointer, it is not something I would be interested in doing right now.

Let me know if you have any thoughts!

**Comment by iazel** [comment]
I see, thank you for the explanation and careful consideration, much appreciated.
